ProvaDBServer/ProvaDBServer/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProvaDBServer.Models
{
    public class Restaurant
    {
        public static List<Restaurant> restaurants = new List<Restaurant>()
        {
            new Restaurant(0, "Le Grand Burger"),
            new Restaurant(1, "Restaurante do seu Telmo"),
            new Restaurant(2, "Atelier de Massas"),
            new Restaurant(3, "Restaurante Anita")
        };

        public int RestaurantId { get; set; }
        [DisplayName("Nome")]
        [Required(ErrorMessage = "Preencha o nome")]
        public string Name { get; set; }

        public Restaurant()
        {
            this.RestaurantId = -1;
            this.Name = "";
        }

        public Restaurant(int restaurantId, string name)
        {
            this.RestaurantId = restaurantId;
            this.Name = name;
        }

        public void Insert ()
        {
            restaurants.Sort((r1, r2) => r1.RestaurantId.CompareTo(r2.RestaurantId));
            restaurants.Add(new Restaurant(restaurants[restaurants.Count - 1].RestaurantId + 1, this.Name));
        }

        public void Update()
        {
            Restaurant getRestaurant = restaurants.Find(t => (t.RestaurantId == this.RestaurantId));
            getRestaurant.Name = this.Name;
        }

        public void Delete()
        {
            restaurants.Remove(this);
        }
    }
}

ProvaDBServer/ProvaDBServer/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProvaDBServer.Models;

namespace ProvaDBServer.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            Restaurant.restaurants.Sort((r1, r2) => r1.Name.CompareTo(r2.Name));

            return View(Restaurant.restaurants);
        }

        public ActionResult Create()
        {
            Restaurant restaurant = new Restaurant();
            return View(restaurant);
        }

        [HttpPost]
        public ActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                restaurant.Insert();

                return ReturnToIndex();
            }

            return View(restaurant);
        }

        public ActionResult Edit(int id)
        {
            List<Restaurant> restaurants = Restaurant.restaurants;
            Restaurant restaurant = restaurants.Find(t => (t.RestaurantId == id));

            return View(restaurant);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                restaurant.Update();

                return ReturnToIndex();
            }

            return View(restaurant);
        }

        public ActionResult Delete(int id)
        {
            List<Restaurant> restaurants = Restaurant.restaurants;
            Restaurant restaurant = restaurants.Find(t => (t.RestaurantId == id));

            return View(restaurant);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int restaurantId)
        {
            List<Restaurant> restaurants = Restaurant.restaurants;
            restaurants.Find(t => (t.RestaurantId == restaurantId)).Delete();
            List<Employee> employees = Employee.employees.FindAll(employee => employee.RestaurantId == restaurantId);
            employees.ForEach(employee => employee.UpdateRestaurant(-1));

            return ReturnToIndex();
        }

        ActionResult ReturnToIndex()
        {
            //TeamRestaurant.Init(true);

            return RedirectToAction("Index");
        }

        public static List<SelectListItem> GetList(Employee employee = null)
        {
            List<SelectListItem> restaurantItems = new List<SelectListItem>();
            if (employee == null)
            {
                bool first = true;
                foreach (Restaurant restaurant in Restaurant.restaurants)
                {
                    restaurantItems.Add(new SelectListItem
                    {
                        Text = restaurant.Name,
                        Value = restaurant.RestaurantId.ToString(),
                        Selected = first
                    });

                    first = false;
                }
            }
            else
            {
                foreach (Restaurant restaurant in Restaurant.restaurants)
                {
                    restaurantItems.Add(new SelectListItem
                    {
                        Text = restaurant.Name,
                        Value = restaurant.RestaurantId.ToString(),
                        Selected = restaurant.RestaurantId == employee.RestaurantId ? true : false
                    });
                }
            }

            return restaurantItems;
        }
    }
}

ProvaDBServer/ProvaDBServer/Views/Restaurant/Create.cshtml
@model ProvaDBServer.Models.Restaurant

@{
    ViewBag.Title = "Create";
}

<h2>Criar Restaurante</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RestaurantId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaDBServer/ProvaDBServer/Views/Restaurant/Delete.cshtml
@model ProvaDBServer.Models.Restaurant

@{
    ViewBag.Title = "Delete";
}

<h3>Você tem certeza que quer deletar essa informação?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Restaurante")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Restaurant", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.RestaurantId)
        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para lista", "Index")
        </div>
    }
</div>

ProvaDBServer/ProvaDBServer/Views/Restaurant/Edit.cshtml
@using System.Web.Optimization
@model ProvaDBServer.Models.Restaurant

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RestaurantId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaDBServer/ProvaDBServer/Views/Restaurant/Index.cshtml
@using ProvaDBServer.Models
@model IEnumerable<ProvaDBServer.Models.Restaurant>

@{
    ViewBag.Title = "Index";
}

<h2>Restaurantes</h2>

<p>
    @Html.ActionLink("Criar novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new {id = item.RestaurantId}) |
            @if (Restaurant.restaurants.Count > 1)
            {
                @Html.ActionLink("Deletar", "Delete", new {id = item.RestaurantId});
            }
        </td>
    </tr>
}

</table>