ProvaDBServer/ProvaDBServer/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProvaDBServer.Models
{
    public class Team
    {
        public static List<Team> teams = new List<Team>()
        {
            new Team(0, "501"),
            new Team(1, "701"),
            new Team(2, "703"),
            new Team(3, "705")
        };

        public int TeamId { get; set; }
        [DisplayName("Nome")]
        [Required(ErrorMessage = "Preencha o nome")]
        public string Name { get; set; }

        public Team()
        {
            this.TeamId = -1;
            this.Name = "";
        }

        public Team(int teamId, string name)
        {
            this.TeamId = teamId;
            this.Name = name;
        }

        public static int GetNumberOfEmployees(int teamId)
        {
            List<Employee> employees = Employee.employees;

            int count = 0;
            foreach (Employee emp in employees)
            {
                if (emp.TeamId == teamId)
                    count++;
            }

            return count;
        }

        public void Insert()
        {
            teams.Sort((r1, r2) => r1.TeamId.CompareTo(r2.TeamId));
            teams.Add(new Team(teams[teams.Count - 1].TeamId + 1, this.Name));
        }

        public void Update()
        {
            Team getTeam = teams.Find(t => (t.TeamId == this.TeamId));
            getTeam.Name = this.Name;
        }

        public void Delete()
        {
            teams.Remove(this);
        }
    }
}

ProvaDBServer/ProvaDBServer/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProvaDBServer.Models;

namespace ProvaDBServer.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult Index()
        {
            Team.teams.Sort((t1, t2) => t1.Name.CompareTo(t2.Name));

            return View(Team.teams);
        }

        public ActionResult Create()
        {
            Team team = new Team();
            return View(team);
        }

        [HttpPost]
        public ActionResult Create(Team team)
        {
            if (ModelState.IsValid)
            {
                team.Insert();

                return ReturnToIndex();
            }

            return View(team);
        }

        public ActionResult Edit(int id)
        {
            List<Team> teams = Team.teams;
            Team team = teams.Find(t => (t.TeamId == id));

            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Team team)
        {
            if (ModelState.IsValid)
            {
                team.Update();

                return ReturnToIndex();
            }

            return View(team);
        }

        public ActionResult Delete(int id)
        {
            List<Team> teams = Team.teams;
            Team team = teams.Find(t => (t.TeamId == id));

            return View(team);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int teamId)
        {
            List<Team> teams = Team.teams;
            teams.Find(t => (t.TeamId == teamId)).Delete();
            List<Employee> employees = Employee.employees.FindAll(employee => employee.TeamId == teamId);
            employees.ForEach(employee => employee.UpdateTeam(-1));

            //return teams[id].name;
            return ReturnToIndex();
        }

        ActionResult ReturnToIndex()
        {
            //TeamRestaurant.Init(true);

            return RedirectToAction("Index");
        }

        public static List<SelectListItem> GetList(Employee employee = null)
        {
            List<SelectListItem> teamItems = new List<SelectListItem>();
            if (employee == null)
            {
                bool first = true;
                foreach (Team team in Team.teams)
                {
                    teamItems.Add(new SelectListItem
                    {
                        Text = team.Name,
                        Value = team.TeamId.ToString(),
                        Selected = first
                    });

                    first = false;
                }
            }
            else
            {
                foreach (Team team in Team.teams)
                {
                    teamItems.Add(new SelectListItem
                    {
                        Text = team.Name,
                        Value = team.TeamId.ToString(),
                        Selected = team.TeamId == employee.TeamId ? true : false
                    });
                }
            }

            return teamItems;
        }

    }
}

ProvaDBServer/ProvaDBServer/Views/Team/Create.cshtml
@model ProvaDBServer.Models.Team

@{
    ViewBag.Title = "Create";
}

<h2>Criar Nova Equipe</h2>

@using (Html.BeginForm()) 
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volta para lista", "Index")
</div>

ProvaDBServer/ProvaDBServer/Views/Team/Delete.cshtml
@model ProvaDBServer.Models.Team

@{
    ViewBag.Title = "Delete";
}

<h3>Você tem certeza que quer deletar essa Equipe?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Equipe")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Team", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.TeamId)
        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para lista", "Index")
        </div>
    }
</div>

ProvaDBServer/ProvaDBServer/Views/Team/Edit.cshtml
@model ProvaDBServer.Models.Team

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>

ProvaDBServer/ProvaDBServer/Views/Team/Index.cshtml
@using ProvaDBServer.Models
@model IEnumerable<ProvaDBServer.Models.Team>

@{
    ViewBag.Title = "Team";
}

<h2>Equipes</h2>

<p>
    @Html.ActionLink("Criar Nova Equipe", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new {id = item.TeamId}) |
            @if (Team.teams.Count > 1)
            {
                @Html.ActionLink("Deletar", "Delete", new { id = item.TeamId });
            }
        </td>
    </tr>
}

</table>